name: Download and Index Bodycam Bundle

permissions:
  actions: read      # ← 필수
  contents: read

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'bodycambundle을 올린 워크플로의 Run ID'
        required: true
        type: string

jobs:
  download-and-index:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false

      # ── 반드시 run-id + 이름이 정확해야 한다 ─────────────────
      - name: Download bodycambundle artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ inputs.run_id }}   # ← 업로드 쪽 run-ID
          name:   bodycambundle         # ← 업로드 시 지정한 이름
          path:   ./downloaded_data
      # ──────────────────────────────────────────────────────────

      - name: Upload to Azure Blob if files exist
        run: |
          if [ -d "./downloaded_data" ] && [ "$(ls -A downloaded_data)" ]; then
            az storage blob upload-batch \
              --account-name   "$AZ_ACCOUNT" \
              --account-key    "$AZ_STORAGE_KEY" \
              --destination    "$AZ_CONTAINER" \
              --source         "./downloaded_data" \
              --if-none-match="*"
            echo "▶ Blob 업로드 완료"
          else
            echo "▶ 다운로드된 artifact가 없습니다. 업로드를 건너뜁니다."
          fi
        env:
          AZ_ACCOUNT:     ${{ secrets.AZ_ACCOUNT }}
          AZ_STORAGE_KEY: ${{ secrets.AZ_STORAGE_KEY }}
          AZ_CONTAINER:   ${{ secrets.AZ_CONTAINER }}

      # 이하 Video Indexer 스텝은 그대로 …
