name: daily-bodycam-fetch

permissions:
  contents: write     # PR에 파일 커밋이 없다면 read 로 줄여도 무방

on:
  schedule:
    - cron: '0 17 * * *'        # 매일 KST 02:00 (UTC 17:00)
  workflow_dispatch:

concurrency:
  group: daily-bodycam-fetch
  cancel-in-progress: true      # 같은 워크플로가 이미 돌고 있으면 최신만 남김

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip                # ← 의존성 캐시

    - name: Install deps
      run: pip install yt-dlp google-api-python-client

      - name: Restore cookies.txt          # ← 추가된 블록
        if: ${{ secrets.YT_COOKIES_B64 != '' }}
        run: |
          echo "${{ secrets.YT_COOKIES_B64 }}" | base64 -d > cookies.txt
          chmod 600 cookies.txt
          echo "cookies.txt restored."

    - name: Run fetch script
      id: run_fetch
      env:
        YT_API_KEY: ${{ secrets.YT_API_KEY }}
      run: python daily_fetch.py

    - name: Upload artifact
      if: steps.run_fetch.outcome == 'success' && hashFiles('data/**/*') != ''
      uses: actions/upload-artifact@v4
      with:
        name: bodycam-bundle
        path: data/**/*
        compression-level: 0      # 대용량 업로드 속도 향상
        retention-days: 14
