name: Test Download-Artifact v2

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      source_run_id:
        description: "테스트용 Run ID"
        required: true
      artifact_name:
        description: "테스트용 아티팩트 이름"
        required: true

jobs:
  test-download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # 실제로는 이미 생성된 다른 워크플로우의 run-id와 artifact name을 넣어야 합니다.
      - name: Download artifact (v2)
        uses: actions/download-artifact@v2
        with:
          run-id: ${{ github.event.inputs.source_run_id }}
          name:   ${{ github.event.inputs.artifact_name }}
          path: ./downloaded_data

      - name: List downloaded files
        run: |
          echo "==== downloaded files ===="
          ls -R ./downloaded_data
