name: Upload to Azure (manual)

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'daily-bodycam-fetch Run ID'
        required: true
        type: number
      artifact_name:
        description: '(선택) 다운로드할 Artifact 이름'
        required: false
        type: string

permissions:
  actions: read
  contents: read

jobs:
  upload-and-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (A) artifact_name이 있으면 → 해당 이름으로만 다운로드
      - name: Download specific artifact
        if: ${{ inputs.artifact_name != '' }}
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ inputs.run_id }}
          name: ${{ inputs.artifact_name }}
          path: ./downloaded_data

      # (B) artifact_name이 빈 문자열이라면 → 전체 다운로드
      - name: Download all artifacts
        if: ${{ inputs.artifact_name == '' }}
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ inputs.run_id }}
          path: ./downloaded_data

      # (C) Azure 로그인
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # (D) 실제 파일이 있으면 업로드, 없으면 건너뜀
      - name: Upload to Azure Blob
        run: |
          if [ -d "./downloaded_data" ] && [ "$(ls -A downloaded_data)" ]; then
            az storage blob upload-batch \
              --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT }}" \
              --account-key  "${{ secrets.AZURE_STORAGE_KEY }}" \
              --destination  "${{ secrets.AZURE_STORAGE_CONTAINER }}" \
              --source       "./downloaded_data" \
              --if-none-match="*"
            echo "▶ Blob 업로드 완료"
          else
            echo "▶ 다운로드된 artifact가 없습니다. 업로드를 건너뜁니다."
          fi

      # (E) Video Indexer도 동일하게 조건부 실행
      - name: Trigger Azure Video Indexer
        env:
          VI_LOCATION:    ${{ secrets.VIDEO_INDEXER_LOCATION }}
          VI_ACCOUNT_ID:  ${{ secrets.VIDEO_INDEXER_ACCOUNT_ID }}
          VI_API_KEY:     ${{ secrets.VIDEO_INDEXER_API_KEY }}
          AZ_ACCOUNT:     ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZ_CONTAINER:   ${{ secrets.AZURE_STORAGE_CONTAINER }}
          AZ_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          if [ ! -d "./downloaded_data" ] || [ -z "$(ls -A downloaded_data)" ]; then
            echo "▶ 업로드할 파일이 없으므로 Video Indexer 요청도 건너뜁니다."
            exit 0
          fi

          ACCESS_TOKEN=$(az rest --method get \
            --uri "https://api.videoindexer.ai/Auth/$VI_LOCATION/Accounts/$VI_ACCOUNT_ID/AccessToken?allowEdit=true" \
            --headers "Ocp-Apim-Subscription-Key:$VI_API_KEY" \
            --output tsv)

          for BLOB in $(az storage blob list \
              --account-name   "$AZ_ACCOUNT" \
              --account-key    "$AZ_STORAGE_KEY" \
              --container-name "$AZ_CONTAINER" \
              --output tsv | cut -f1); do

            if [[ $BLOB =~ \.(mp4|mov|m4a|wav)$ ]]; then
              VIDEO_URL="https://$AZ_ACCOUNT.blob.core.windows.net/$AZ_CONTAINER/$BLOB"
              echo "• Indexing $VIDEO_URL"
              az rest --method post \
                --uri "https://api.videoindexer.ai/$VI_LOCATION/Accounts/$VI_ACCOUNT_ID/Videos" \
                --headers "Content-Type:application/json" \
                --body "{\"accessToken\":\"$ACCESS_TOKEN\",\"name\":\"$(basename "$BLOB")\",\"videoUrl\":\"$VIDEO_URL\"}" \
                --output none
              sleep 2
            fi
          done

          echo "▶ Video Indexer 요청 완료"
