name: Upload to Azure (단독 실행용)

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'daily-bodycam-fetch 워크플로의 Run ID'
        required: true
        type: number
      artifact_name:
        description: '아티팩트 이름 (예: bodycam-bundle-25)'
        required: true
        type: string

permissions:
  actions: read
  contents: read

jobs:
  upload-and-index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 아티팩트 → ./downloaded_data 로 풀기
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ inputs.run_id }}
          name:   ${{ inputs.artifact_name }}
          path:   ./downloaded_data          # ← 경로 통일

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Blob
        run: |
          az storage blob upload-batch \
            --account-name   "${{ secrets.AZURE_STORAGE_ACCOUNT }}" \
            --account-key    "${{ secrets.AZURE_STORAGE_KEY }}" \
            --destination    "${{ secrets.AZURE_STORAGE_CONTAINER }}" \
            --source         "./downloaded_data" \
            --if-none-match="*"
          echo "▶ Blob 업로드 완료"

      - name: Trigger Azure Video Indexer
        env:
          VI_LOCATION:   ${{ secrets.VIDEO_INDEXER_LOCATION }}
          VI_ACCOUNT_ID: ${{ secrets.VIDEO_INDEXER_ACCOUNT_ID }}
          VI_API_KEY:    ${{ secrets.VIDEO_INDEXER_API_KEY }}
          AZ_ACCOUNT:    ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZ_CONTAINER:  ${{ secrets.AZURE_STORAGE_CONTAINER }}
          AZ_STORAGE_KEY:${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          ACCESS_TOKEN=$(az rest --method get \
            --uri "https://api.videoindexer.ai/Auth/$VI_LOCATION/Accounts/$VI_ACCOUNT_ID/AccessToken?allowEdit=true" \
            --headers "Ocp-Apim-Subscription-Key:$VI_API_KEY" \
            --output tsv)

          for BLOB in $(az storage blob list \
              --account-name "$AZ_ACCOUNT" \
              --account-key  "$AZ_STORAGE_KEY" \
              --container-name "$AZ_CONTAINER" \
              --query "[].name" -o tsv); do
            if [[ $BLOB =~ \.(mp4|mov|m4a|wav)$ ]]; then
              VIDEO_URL="https://$AZ_ACCOUNT.blob.core.windows.net/$AZ_CONTAINER/$BLOB"
              echo "• Indexing $VIDEO_URL"
              az rest --method post \
                --uri "https://api.videoindexer.ai/$VI_LOCATION/Accounts/$VI_ACCOUNT_ID/Videos" \
                --headers "Content-Type:application/json" \
                --body "{\"accessToken\":\"$ACCESS_TOKEN\",\"name\":\"$(basename "$BLOB")\",\"videoUrl\":\"$VIDEO_URL\"}" \
                --output none
            fi
          done
          echo "▶ Video Indexer 요청 완료"
