name: Upload to Azure Blob Storage

on:
  workflow_run:
    workflows: ["daily-bodycam-fetch"]
    types: [completed]

jobs:
  upload-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download bodycam artifact
        uses: actions/download-artifact@v3
        with:
          name: bodycam-bundle-${{ github.event.workflow_run.run_number }}
          path: data

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload entire data/ folder to Blob Storage (skip existing)
        run: |
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --destination ${{ secrets.AZURE_CONTAINER_NAME }} \
            --source ./data \
            --auth-mode login \
            --overwrite false \
            --no-progress

      - name: List uploaded blobs
        run: |
          az storage blob list \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --container-name ${{ secrets.AZURE_CONTAINER_NAME }} \
            --query "[].{name:name}" \
            -o table
